DROP TABLE IF EXISTS camera;
DROP TABLE IF EXISTS events;

CREATE TABLE camera (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT NOT NULL
);

CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  camera_id INTEGER NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (camera_id) REFERENCES camera (id)
);
